import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import PopupProvider from "@/components/Popup/Provider";
import { UserSession } from "@/components/shared/UserSession";
import { SessionProvider } from "next-auth/react";
import { getSession } from "@/lib/db";
import { SocketProvider } from "@/context/SocketProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <UserSession />
          <Header />
          {children}
          <PopupProvider />
        </SocketProvider>
      </body>
    </html>
  );
}
